name: Test selected versions on a schedule

on:
  push:
    branches:
      - test-scheduled
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "examples/**"
      - "templates/**"
  schedule:
    - cron: "0 12 * * 1" # 12:00 every Monday.

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        tag: 
          - "nightly"

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_wrapper: false

      - name: Start Pi-hole
        shell: bash
        env:
          TAG: ${{ matrix.tag }}
        run: make docker-run

      - name: Run tests
        env:
          PIHOLE_URL: http://localhost:8080
          PIHOLE_PASSWORD: test
        run: make testall
